Repository astroML/astroML, pull requests merged in 2019-03, with the labels that each got.

#169 Fix decorator
  .travis.yml
  astroML/utils/decorators.py
Labels: bug, infrastructure, merge-when-ci-passes, no-changelog-entry-needed

#121 Rebased version of #35: Use astropy.cosmology instead of built-in cosmology when possible
  astroML/cosmology.py
  astroML/datasets/generated.py
  astroML/datasets/sdss_specgals.py
Labels: refactoring

#164 Enabling doctesting
  .travis.yml
  astroML/datasets/LIGO_bigdog.py
  astroML/datasets/LINEAR_sample.py
  astroML/datasets/dr7_quasar.py
  astroML/datasets/imaging_sample.py
  astroML/datasets/moving_objects.py
  astroML/datasets/rrlyrae_mags.py
  astroML/datasets/sdss_S82standards.py
  astroML/datasets/sdss_specgals.py
  astroML/datasets/sdss_spectrum.py
  astroML/datasets/sdss_sspp.py
  astroML/density_estimation/bayesian_blocks.py
  astroML/filters.py
  astroML/fourier.py
  astroML/linear_model/TLS.py
  astroML/plotting/tools.py
  astroML/stats/_binned_statistic.py
  astroML/time_series/tests/test_periodogram.py
  astroML/utils/decorators.py
  astroML/utils/tests/test_utils.py
  pytest.ini
  setup.cfg
Labels: infrastructure, no-changelog-entry-needed

#172 Cosmology minor cleanup
  astroML/datasets/generated.py
  astroML/datasets/sdss_specgals.py
Labels: merge-when-ci-passes, no-changelog-entry-needed

#136 Fix warnings and add more matplotlib rc changes
  astroML/filters.py
  astroML/plotting/settings.py
Labels: no-changelog-entry-needed, refactoring

#173 Adding deprecations from periodograms
  astroML/time_series/periodogram.py
Labels: time_series

#176 z as band is not the same as z as redshift
  .travis.yml
  astroML/datasets/sdss_specgals.py
  astroML/datasets/tests/__init__.py
  astroML/datasets/tests/test_datasets.py
Labels: bug

#177 wheel format compatibility
  setup.py
Labels: infrastructure
