Repository astroML/astroML, pull requests merged in 2019-06, with the labels that each got.

#182 increase test coverage
  astroML/classification/gmm_bayes.py
  astroML/classification/tests/test_gmm_bayes.py
  astroML/linear_model/tests/test_kernel_regression.py
  astroML/tests/test_correlation.py
  astroML/utils/tests/test_utils.py
  doc/user_guide/correlation_functions.rst
Labels: no-changelog-entry-needed, testing

#192 Cleaning up sklearn <0.14 workaround
  astroML/correlation.py
  astroML/datasets/tools/cas_query.py
Labels: merge-when-ci-passes, no-changelog-entry-needed, refactoring

#193 Deprecate savitzky_golay
  astroML/filters.py
  astroML/tests/test_filters.py
  doc/user_guide/installation.rst
Labels: refactoring

#190 Deprecate utils.check_random_state
  CHANGES.rst
  astroML/correlation.py
  astroML/datasets/generated.py
  astroML/density_estimation/empirical.py
  astroML/density_estimation/xdeconv.py
  astroML/resample.py
  astroML/time_series/generate.py
  astroML/time_series/periodogram.py
  astroML/utils/tests/test_utils.py
  astroML/utils/utils.py
Labels: refactoring
