Repository astroML/astroML, pull requests merged in 2020-03, with the labels that each got.

#208 Replace http:// with https://
  README.rst
Labels: no-changelog-entry-needed

#210 Update requirements
  .travis.yml
  doc/user_guide/installation.rst
  setup.py
Labels: docs, no-changelog-entry-needed

#206 Regression with errors
  .travis.yml
  CHANGES.rst
  astroML/conftest.py
  astroML/datasets/__init__.py
  astroML/datasets/kelly2007test.py
  astroML/linear_model/__init__.py
  astroML/linear_model/linear_regression_errors.py
  astroML/linear_model/tests/test_linear_regression.py
  setup.cfg
Labels: merge-when-ci-passes

#213 MNT: Set max-line-length for flake8
  setup.cfg
Labels: no-changelog-entry-needed
